# Generated by Django 3.0.3 on 2024-11-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я автора")),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name="Ім'я автора")),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name="Ім'я автора")),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Біографія')),
                ('biography_uk', models.TextField(blank=True, null=True, verbose_name='Біографія')),
                ('biography_en', models.TextField(blank=True, null=True, verbose_name='Біографія')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актеры и режиссеры',
                'verbose_name_plural': 'Актеры и режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва книги')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Назва книги')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Назва книги')),
                ('description', models.TextField(verbose_name='Опис')),
                ('description_uk', models.TextField(null=True, verbose_name='Опис')),
                ('description_en', models.TextField(null=True, verbose_name='Опис')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обкладинка')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('draft', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.ManyToManyField(to='movies.Author', verbose_name='Автори')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Ілюстрація')),
                ('image_uk', models.ImageField(null=True, upload_to='book_images/', verbose_name='Ілюстрація')),
                ('image_en', models.ImageField(null=True, upload_to='book_images/', verbose_name='Ілюстрація')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.Book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры из фильма',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Користувач')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.Book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанри'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва категорії'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва жанру'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default='Unknown User', max_length=255, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва жанру'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва жанру'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieShots',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='Жанри'),
        ),
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.Book', verbose_name='Книга'),
        ),
    ]
