# Generated by Django 3.0.3 on 2024-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
    ]
