# Generated by Django 3.0.3 on 2024-11-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_book_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Відгуки', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='movies.Review', verbose_name='Батьківський відгук'),
        ),
    ]
