# Generated by Django 3.0.3 on 2024-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20241126_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган книги'),
        ),
    ]
