# Generated by Django 3.0.3 on 2024-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_book_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік'),
        ),
    ]
